/// Flutter icons CostomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CostomIcons
///      fonts:
///       - asset: fonts/CostomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CostomIcons {
  CostomIcons._();

  static const _kFontFam = 'CostomIcons';
  static const String? _kFontPkg = null;

  static const IconData muscle_wd7nyxe8dhrx =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success_ifcteb55zwwt =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_4fzqtvt977t1 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
